title: Namita Chhabra
logo: "/Profile_Picture.png"
description: I am an enthusiastic hard worker and aspiring Data Analyst whose interests lie in data science and applied statistics. I look forward to analyzing your data! <br><br> <a href="https://www.linkedin.com/in/nc9780/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal

